fix crash when zero byte data is pushed into resampler
when a 0 byte array is pushed into AudioResampler, it raises:

ValueError: Buffer size too small (0 instead of at least 1 bytes)